(define (cont-frac n d k)
  (define (frac i)
    (if (= i k)
        (/ (n i) (d i))
        (/ (n i)
           (+ (d i) (frac (+ i 1))))))
  (frac 1))

(define (cont-frac-it n d k)
  (define (frac i res)
    (newline)
    (display res)
    (if (= i 1)
        (/ (n i) res)
        (frac (- i 1) (+ (d (- i 1)) (/ (n i) res)))))
  (frac k 1))